### ISSUE TITLE
ScanNet train/test split

### ISSUE THREAD

**Issue by ymingxie** [xxlong0/CNMNet#3]
Hello,
 
According to your paper, you divided ScanNet scenes into 1000 for training and 600 for testing.

But I wonder why file train_plane_view3_scans0_999_interval2_error01.txt only has 882 scenes?

**Comment by flamehaze1115** [comment]
That's because there are no planes detected in some scenes.

Best
Xiaoxiao
________________________________
发件人: ymingxie <notifications@github.com>
发送时间: Monday, November 9, 2020 12:01:59 AM
收件人: xxlong0/CNMNet <CNMNet@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [xxlong0/CNMNet] ScanNet train/test split (#3)


Hello,

According to your paper, you divided ScanNet scenes into 1000 for training and 600 for testing.

But I wonder why file train_plane_view3_scans0_999_interval2_error01.txt only has 882 scenes?

―
